name: ServerSelector2
main: net.azisaba.lobby.serverselector2.ServerSelector
version: ${project.version}
authors: [siloneco, YukiLeafX]
description: ${project.description}
website: ${project.url}
permissions:
  serverselector.receive:
    default: false
