name: ${project.name}
main: net.azisaba.lobby.serverselector.ServerSelector
version: ${project.version}
author: siloneco
description: ${project.description}
website: ${project.url}
api-version: 1.13
permissions:
  serverselector.clearinv.exempt:
    default: op